### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by sztibi82** [nopnop2002/wiringpi-tft-tool#3]
Hi  NopNop2002.

Tried to compile a fresh download from github, and i get the following error.
Please can you advice how to overcome the error
![image](https://user-images.githubusercontent.com/35861226/35469085-18c50752-0336-11e8-81b2-91f135408f89.png)

Thanks

**Comment by nopnop2002** [comment]
Thank you for your report.
I fixed it.

**Comment by sztibi82** [comment]
Thanks for the quick fix. Great work. :)

**Comment by sztibi82** [comment]
Do you think that we can drive with this library the following?
https://www.waveshare.com/product/modules/oleds-lcds/raspberry-pi-lcd/3.5inch-rpi-lcd-a.htm

As far as I know it has an ILI9486

**Comment by nopnop2002** [comment]
There is no information about driver chip.

When a driver chip isn't understood, it gives up.

**Comment by sztibi82** [comment]
I requested more information from manufacturer. Will come back with more info when received.

**Comment by nopnop2002** [comment]
OK
Thank you.

**Comment by yacc123** [comment]
Hi, is this possible to show on lcd a result of shell command? e.g. date, uptime ?

**Comment by nopnop2002** [comment]
@yacc123

Yes
I added me.sh.

**Comment by yacc123** [comment]
great, thanks :)
