### ISSUE TITLE
2.6" ILI9342

### ISSUE THREAD

**Issue by 32teeth** [nopnop2002/wiringpi-tft-tool#4]
Came across your repo, great stuff.
Managed to get the 2.8" ILI9341 working well 

### My question is for the ILI9342
I have this 2.6" 37PIN ILI9342
<img src="https://ae01.alicdn.com/kf/HTB1kqjkPFXXXXX7aXXXq6xXFXXX1/206109602/HTB1kqjkPFXXXXX7aXXXq6xXFXXX1.jpg">

Which has this pinout
<img src="https://ae01.alicdn.com/kf/HTB1siroPFXXXXcXXVXXq6xXFXXXq/206109602/HTB1siroPFXXXXcXXVXXq6xXFXXXq.jpg">

I can seem to get it to work with the pin mapping you defined
Any help or insight would be great!

[link to product on AliExpress](https://www.aliexpress.com/item/2-6-inch-2-5-inch-Widescreen-37pin-display-320-240-LCD-MCU-8bit-16bit-TFT/32793445466.html?spm=a2g0s.9042311.0.0.21344c4dly6ksD)

**Comment by nopnop2002** [comment]
Your TFT is 16 Bit Parallel I/F.
This library is NOT support 16 Bit Parallel I/F.

**Comment by 32teeth** [comment]
Description says 
'NoEnName_Null 2.6 inch 2.5 inch Widescreen 37pin display 320*240 LCD MCU **8bit** 16bit TFT'

**Comment by nopnop2002** [comment]
If it work using 8 bit Parallel I/F, Probably DB0-DB7 become a data pin.

But I have not tried.

**Comment by 32teeth** [comment]
Can i run this with 
```
con2fbmap 1 1
```

to mirror hdmi?

**Comment by nopnop2002** [comment]
No
This library doesn't use frame buffer.
